### ISSUE TITLE
Deferred example crashes on windows with D3D 11

### ISSUE THREAD

**Issue by Diggsey** [gfx-rs/gfx#1065]
Backtrace:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DescriptorInit(VertexImport("a_Pos", None))', ../src/libcore\result.rs:799
stack backtrace:
   0:     0x7ff6895c7814 - <std::io::error::ErrorKind as core::fmt::Debug>::fmt::h84f2c20f56ab6db2
   1:     0x7ff6895c5d53 - std::rt::lang_start::h14cbded5fe3cd915
   2:     0x7ff6895c66bd - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   3:     0x7ff6895c6556 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   4:     0x7ff6895c6474 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   5:     0x7ff6895c640b - rust_begin_unwind
   6:     0x7ff6895d0255 - core::panicking::panic_fmt::h9af671b78898cdba
   7:     0x7ff68944c873 - core::result::unwrap_failed<gfx::factory::PipelineStateError<collections::string::String>>
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libcore\macros.rs:29
   8:     0x7ff689445739 - core::result::Result<gfx::pso::PipelineState<gfx_device_dx11::Resources, deferred::emitter::Meta>, gfx::factory::PipelineStateError<collections::string::String>>::unwrap<gfx::pso::PipelineState<gfx_device_dx11::Resources, deferred::emitter::Meta>,gfx::factory::PipelineStateError<collections::string::String>>
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libcore\result.rs:737
   9:     0x7ff68946b7f2 - deferred::{{impl}}::new<gfx_device_dx11::Resources,gfx_device_dx11::factory::Factory>
                        at C:\Users\diggs\workspace\gfx\examples\deferred\main.rs:326
  10:     0x7ff689432217 - gfx_app::{{impl}}::new<gfx_device_dx11::Resources,gfx_device_dx11::command::CommandBuffer<gfx_device_dx11::DeferredContext>,deferred::App<gfx_device_dx11::Resources>,gfx_device_dx11::factory::Factory>
                        at C:\Users\diggs\workspace\gfx\src\lib.rs:167
  11:     0x7ff6894431a8 - gfx_app::{{impl}}::launch<gfx_app::Wrap<gfx_device_dx11::Resources, gfx_device_dx11::command::CommandBuffer<gfx_device_dx11::DeferredContext>, deferred::App<gfx_device_dx11::Resources>>>
                        at C:\Users\diggs\workspace\gfx\src\lib.rs:268
  12:     0x7ff689460331 - gfx_app::Application::launch_default<deferred::App<gfx_device_dx11::Resources>,gfx_device_dx11::Resources>
                        at C:\Users\diggs\workspace\gfx\src\lib.rs:117
  13:     0x7ff68946f85c - deferred::main
                        at C:\Users\diggs\workspace\gfx\examples\deferred\main.rs:567
  14:     0x7ff6895c9ce1 - _rust_maybe_catch_panic
  15:     0x7ff6895c578a - std::rt::lang_start::h14cbded5fe3cd915
  16:     0x7ff689493179 - main
  17:     0x7ff6895d5b67 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264
  18:     0x7ff957008363 - BaseThreadInitThunk
error: process didn't exit successfully: `target\debug\examples\deferred.exe test` (exit code: 101)
```

I was able to run the application successfully with opengl. The cube and other examples ran fine under D3D 11.

**Comment by kvark** [comment]
Thanks for the report! Looks like the shader reflection is failing to find `a_Pos` attribute.

**Comment by kvark** [comment]
Actually, it doesn't make sense. The relevant PSO is `blit`, and it doesn't use `a_Pos`, and neither the shader has it.

**Comment by msiglreith** [comment]
The `*.fx` shader files for the deferred example are outdated and need to be rebuilt. I'm going to setup a PR.
