### ISSUE TITLE
Cannot update vertex buffer in gfx 0.13: InvalidOperation

### ISSUE THREAD

**Issue by kryptan** [gfx-rs/gfx#1107]
I have a simple demo app here - https://github.com/kryptan/gfx-test
It is a simple rotating triangle. Branch `working` is based on gfx 0.12 and is working while branch `master` which is based on recently released gfx 0.13 panics:

```
thread 'main' panicked at 'Error after executing command UpdateBuffer(1, DataPointer { offset: 0, size: 72 }, 0): InvalidOperation', C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx_device_gl-0.12.0\src\lib.rs:337
stack backtrace:
   0:     0x7ff6d396ab84 - <std::sync::mpsc::RecvError as core::fmt::Debug>::fmt::h644c369fc7e7b3cf
   1:     0x7ff6d39690b3 - std::rt::lang_start::h538f8960e7644c80
   2:     0x7ff6d3969a7d - std::panicking::rust_panic_with_hook::hc303199e04562edf
   3:     0x7ff6d3969916 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   4:     0x7ff6d3969834 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   5:     0x7ff6d3947c8f - gfx_device_gl::Device::check
                        at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx_device_gl-0.12.0\src\lib.rs:337
   6:     0x7ff6d3949c0b - gfx_device_gl::Device::process
                        at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx_device_gl-0.12.0\src\lib.rs:774
   7:     0x7ff6d394c8bf - gfx_device_gl::Device::no_fence_submit
                        at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx_device_gl-0.12.0\src\lib.rs:780
   8:     0x7ff6d394d606 - gfx_device_gl::{{impl}}::submit
                        at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx_device_gl-0.12.0\src\lib.rs:901
   9:     0x7ff6d387c701 - gfx::encoder::Encoder<gfx_device_gl::Resources, gfx_device_gl::command::CommandBuffer>::flush<gfx_device_gl::Resources,gfx_device_gl::command::CommandBuffer,gfx_device_gl::Device>
                        at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.13.0\src\encoder.rs:112
  10:     0x7ff6d388c9d1 - gfx_test::main
                        at E:\mega3\projects\gfx-test\src\main.rs:99
  11:     0x7ff6d396d051 - _rust_maybe_catch_panic
  12:     0x7ff6d3968aea - std::rt::lang_start::h538f8960e7644c80
  13:     0x7ff6d3890ba9 - main
  14:     0x7ff6d3977568 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  15:     0x7ffbcee18363 - BaseThreadInitThunk
error: process didn't exit successfully: `target\debug\gfx-test.exe` (exit code: 101)
```

The only thing I did to port to a new version was changing this line:

    let index_buffer = factory.create_buffer_const(&indices, gfx::BufferRole::Index, gfx::Bind::empty()).unwrap();

to this one:

    let index_buffer = factory.create_buffer_immutable(&indices, gfx::buffer::Role::Index, gfx::Bind::empty()).unwrap();

I'm not sure I did everything correctly but I guess it still shouldn't panic anyway.

**Comment by Bastacyclop** [comment]
@kryptan Hey, you should not be updating (mutating) an immutable buffer, try `create_buffer_dynamic` or another buffer usage. We should detect that and return a proper error.

**Comment by kryptan** [comment]
@Bastacyclop Thanks, I replaced 

    let vertex_buffer = factory.create_vertex_buffer(&vertices);

with

    let vertex_buffer = factory.create_buffer_dynamic(vertices.len(), gfx::buffer::Role::Vertex, gfx::Bind::empty()).unwrap();

and it is now working. I think documentation for `create_vertex_buffer` should mention that it creates immutable buffer.

**Comment by kvark** [comment]
We need to catch this error before calling GL and return properly. Leaving this bug open until we do.
