### ISSUE TITLE
[DX11] All examples crash when window is minimized

### ISSUE THREAD

**Issue by marek-g** [gfx-rs/gfx#1156]
Windows / DX11 / Gfx-0.14.0 and master branch, too.

gfx_window_dxgi::window.swap_buffers() panics at 'assertion failed: `(left == right)` (left: `0`, right: `142213121`)'. This happens when you minimize application window. Can be reproduced on every example code.

**Comment by msiglreith** [comment]
Backtrace:
```
E:\Desktop\repository\gfx>cargo run --example cube
    Finished debug [unoptimized + debuginfo] target(s) in 0.2 secs
     Running `target\debug\examples\cube.exe`
ERROR:gfx_app: Resize failed with code 887A0001
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `0`, right: `142213121`)', src\window\dxgi\src\lib.rs:46
stack backtrace:
   0:     0x7ff79b72cd5a - std::panicking::default_hook::{{closure}}
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:354
   1:     0x7ff79b72c266 - std::panicking::default_hook
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:365
   2:     0x7ff79b72fc3d - std::panicking::rust_panic_with_hook
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:553
   3:     0x7ff79b72fa88 - std::panicking::begin_panic<collections::string::String>
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:515
   4:     0x7ff79b72f9f4 - std::panicking::begin_panic_fmt
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:499
   5:     0x7ff79b667e5e - gfx_window_dxgi::Window::swap_buffers
                        at E:\Desktop\repository\gfx\src\window\dxgi\src\lib.rs:46
   6:     0x7ff79b51a532 - gfx_app::launch_d3d11<gfx_app::Wrap<gfx_device_dx11::Resources, gfx_device_dx11::command::CommandBuffer<gfx_device_dx11::DeferredContext>, cube::App<gfx_device_dx11::Resources>>>
                        at E:\Desktop\repository\gfx\src\lib.rs:235
   7:     0x7ff79b51993c - gfx_app::Application::launch_default<cube::App<gfx_device_dx11::Resources>,gfx_device_dx11::Resources>
                        at E:\Desktop\repository\gfx\src\lib.rs:369
   8:     0x7ff79b51974a - gfx_app::Application::launch_simple<cube::App<gfx_device_dx11::Resources>,gfx_device_dx11::Resources>
                        at E:\Desktop\repository\gfx\src\lib.rs:361
   9:     0x7ff79b5251ec - cube::main
                        at E:\Desktop\repository\gfx\examples\cube\main.rs:184
  10:     0x7ff79b730991 - panic_unwind::__rust_maybe_catch_panic
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libpanic_unwind\lib.rs:98
  11:     0x7ff79b72fefa - std::rt::lang_start
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\rt.rs:51
  12:     0x7ff79b52e16b - main
  13:     0x7ff79b73ce08 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  14:     0x7ff9746d8363 - BaseThreadInitThunk
```

DXGI_STATUS_OCCLUDED (0x887A0001 == 142213121)
 https://msdn.microsoft.com/de-de/library/windows/desktop/cc308061(v=vs.85).aspx
