### ISSUE TITLE
Instancing example crashes on Windows

### ISSUE THREAD

**Issue by vitvakatu** [gfx-rs/gfx#1306]
Here is backtrace:
```
    Finished dev [unoptimized + debuginfo] target(s) in 1.4 secs
     Running `target\debug\examples\instancing.exe`
32 instances per length
1024 instances
size: 0.05
gap: 0.012121213
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DescriptorInit(VertexImport("a_Color", Some(Format(R32, Uint))))', src\libcore\result.rs:859
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<collections::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:495
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:471
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:69
   8: core::result::unwrap_failed<gfx::factory::PipelineStateError<collections::string::String>>
             at C:\projects\rust\src\libcore\macros.rs:29
   9: core::result::Result<gfx::pso::PipelineState<gfx_device_dx11::Resources, instancing::pipe::Meta>, gfx::factory::PipelineStateError<collections::string::String>>::unwrap<gfx::pso::PipelineState<gfx_device_dx11::Resources, instancing::pipe::Meta>,gfx::factory::PipelineStateError<collections::string::String>>
             at C:\projects\rust\src\libcore\result.rs:737
  10: instancing::{{impl}}::new<gfx_device_dx11::Resources,gfx_device_dx11::factory::Factory>
             at .\examples\instancing\main.rs:137
  11: gfx_app::{{impl}}::new<gfx_device_dx11::Resources,gfx_device_dx11::command::CommandBuffer<gfx_device_dx11::DeferredContext>,instancing::App<gfx_device_dx11::Resources>,gfx_device_dx11::factory::Factory>
             at .\src\lib.rs:405
  12: gfx_app::launch_d3d11<gfx_app::Wrap<gfx_device_dx11::Resources, gfx_device_dx11::command::CommandBuffer<gfx_device_dx11::DeferredContext>, instancing::App<gfx_device_dx11::Resources>>>
             at .\src\lib.rs:199
  13: gfx_app::Application::launch_default<instancing::App<gfx_device_dx11::Resources>,gfx_device_dx11::Resources>
             at .\src\lib.rs:378
  14: instancing::main
             at .\examples\instancing\main.rs:178
  15: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  16: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  17: main
  18: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  19: BaseThreadInitThunk
error: process didn't exit successfully: `target\debug\examples\instancing.exe` (exit code: 101)
```

System info:
Windows 8.1

**Comment by vitvakatu** [comment]
After some investigation I found the point where this went wrong. I almost sure it's PR #1262
