### ISSUE TITLE
Panic when running examples using Vulkan backend

### ISSUE THREAD

**Issue by ConorLPBoyle** [gfx-rs/gfx#1382]
Attemping to run standard backend examples with Windows 10 MSVC using `--features vulkan` failed with a backtrace leading up to a vk.CreateImage call:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `3294956295`', src\backend\vulkan\src\factory.rs:804:8
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
...
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:521
   6: gfx_device_vulkan::factory::{{impl}}::create_texture_raw
             at .\src\backend\vulkan\src\factory.rs:804
   7: gfx_core::factory::Factory::create_texture<gfx_device_vulkan::factory::Factory,gfx_device_vulkan::Resources,gfx_core::format::D24_S8>
             at .\src\core\src\factory.rs:309
   8: gfx_core::factory::Factory::create_depth_stencil<gfx_device_vulkan::factory::Factory,gfx_device_vulkan::Resources,(gfx_core::format::D24_S8, gfx_core::format::Unorm)>
             at .\src\core\src\factory.rs:458
   9: gfx_app::launch_vulkan<gfx_app::Wrap<gfx_device_vulkan::Resources, gfx_device_vulkan::command::Buffer, cube::App<gfx_device_vulkan::Resources>>>
             at .\src\lib.rs:345
  10: gfx_app::Application::launch_default<cube::App<gfx_device_vulkan::Resources>,gfx_device_vulkan::Resources>
             at .\src\lib.rs:424
  11: gfx_app::Application::launch_simple<cube::App<gfx_device_vulkan::Resources>,gfx_device_vulkan::Resources>
             at .\src\lib.rs:408
  12: cube::main
             at .\examples\cube\main.rs:183
...
  17: BaseThreadInitThunk
error: process didn't exit successfully: `target\debug\examples\cube.exe` (exit code: 101)
```

Output after setting `VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation`:
```
MEM(ERROR): object: 0x218257df5e0 type: 6 location: 6500 msgCode: 103: Calling vkBeginCommandBuffer() on active command buffer 0x00000218257DF5E0 before it has completed. You must check command buffer fence before this call. For more information refer to Vulkan Spec Section '5.4. Command Buffer Recording' which states 'commandBuffer must not be in the recording or pending state.' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkBeginCommandBuffer)
DS(ERROR): object: 0x218257df5e0 type: 6 location: 5438 msgCode: 96: Attempt to free command buffer (0x00000218257DF5E0) which is in use. For more information refer to Vulkan Spec Section '5.3. Command Buffer Allocation and Management' which states 'All elements of pCommandBuffers must not be in the pending state' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkFreeCommandBuffers)
ParameterValidation(ERROR): object: 0x0 type: 0 location: 118 msgCode: 1: vkCreateImage: parameter pCreateInfo->extent.depth must be greater than 0
ParameterValidation(ERROR): object: 0x0 type: 0 location: 2536 msgCode: 2130: vkCreateImage(): if pCreateInfo->imageType is VK_IMAGE_TYPE_2D, pCreateInfo->extent.depth must be 1. For more information refer to Vulkan Spec Section '11.3. Images' which states 'If imageType is VK_IMAGE_TYPE_2D, extent.depth must be 1' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkImageCreateInfo)
Image(ERROR): object: 0x0 type: 10 location: 707 msgCode: 2917: CreateImage extent is 0 for at least one required dimension for image: Width = 1024 Height = 768 Depth = 0. For more information refer to Vulkan Spec Section '11.3. Images' which states 'If the pNext chain contains an instance of VkExternalMemoryImageCreateInfoNV, it must not contain an instance of VkExternalMemoryImageCreateInfoKHX.' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkImageCreateInfo)
Image(ERROR): object: 0x0 type: 10 location: 766 msgCode: 731: vkCreateImage parameter, pCreateInfo->initialLayout, must be VK_IMAGE_LAYOUT_UNDEFINED or VK_IMAGE_LAYOUT_PREINITIALIZED. For more information refer to Vulkan Spec Section '11.3. Images' which states 'initialLayout must be a valid VkImageLayout value' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VUID-VkImageCreateInfo-initialLayout-00993)
```

**Comment by msiglreith** [comment]
This is expected. The current vulkan backend (not vulkanll) is not working and will be updated alongside the ll integration process. Thanks for reporting though!

The only vulkan example which should work atm is `trianglell` based on the `vulkanll` backend.

**Comment by ConorLPBoyle** [comment]
I figured as much, seeing that its dependency is [over 1000 commits behind](https://github.com/sectopod/vulkano).

**Comment by msiglreith** [comment]
Outdated. We rewritten the vulkan backend based on the new hal api.
