### ISSUE TITLE
Can't compile in the root directory.

### ISSUE THREAD

**Issue by Ploppz** [gfx-rs/gfx#1454]
```
$ cargo doc --open --all
   Compiling itertools v0.5.10
 Documenting itertools v0.5.10
 Documenting comptr v0.1.0 (https://github.com/msiglreith/comptr-rs.git?branch=gfx#42900977)
   Compiling comptr v0.1.0 (https://github.com/msiglreith/comptr-rs.git?branch=gfx#42900977)
   Compiling gfx_corell v0.1.1 (file:///home/ploppz/work/rust/GFX/gfx/src/corell)
   Compiling objc_exception v0.1.1
   Compiling core-foundation-sys v0.3.1
 Documenting gfx_corell v0.1.1 (file:///home/ploppz/work/rust/GFX/gfx/src/corell)
 Documenting user32-sys v0.2.0
 Documenting advapi32-sys v0.2.0
 Documenting user32-sys v0.1.2
 Documenting dxgi-sys v0.2.0 (https://github.com/msiglreith/winapi-rs.git?branch=gfx#f57e1da0)
error: failed to run custom build command for `objc_exception v0.1.1`
process didn't exit successfully: `/home/ploppz/work/rust/GFX/gfx/target/debug/build/objc_exception-8f69aaeb17a5413e/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-o" "/home/ploppz/work/rust/GFX/gfx/target/debug/build/objc_exception-17e3cc0724c8939b/out/extern/exception.o" "-c" "extern/exception.m"
cargo:warning=cc: error trying to exec 'cc1obj': execvp: No such file or directory
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-o" "/home/ploppz/work/rust/GFX/gfx/target/debug/build/objc_exception-17e3cc0724c8939b/out/extern/exception.o" "-c" "extern/exception.m" with args "cc" did not execute successfully (status code exit code: 1).

', /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.53/src/lib.rs:1659:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: gcc::fail
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.53/src/lib.rs:1659
   8: gcc::Build::compile
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.53/src/lib.rs:776
   9: gcc::compile_library
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.53/src/lib.rs:242
  10: build_script_build::main
             at ./build.rs:4
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  13: main
  14: __libc_start_main
  15: _start

warning: build failed, waiting for other jobs to finish...
error[E0432]: unresolved import `winapi::IUnknown`
 --> /home/ploppz/.cargo/git/checkouts/comptr-rs-b0e87f92a80797e2/4290097/src/lib.rs:8:5
  |
8 | use winapi::IUnknown;
  |     ^^^^^^^^^^^^^^^^ no `IUnknown` in the root

error[E0432]: unresolved import `winapi::IUnknown`
 --> /home/ploppz/.cargo/git/checkouts/comptr-rs-b0e87f92a80797e2/4290097/src/lib.rs:8:5
  |
8 | use winapi::IUnknown;
  |     ^^^^^^^^^^^^^^^^ no `IUnknown` in the root

error: aborting due to previous error

error: Compilation failed, aborting rustdoc

error: native frameworks are only available on macOS targets

error: aborting due to previous error

error: Could not compile `comptr`.
warning: build failed, waiting for other jobs to finish...
error: Could not document `comptr`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name comptr /home/ploppz/.cargo/git/checkouts/comptr-rs-b0e87f92a80797e2/4290097/src/lib.rs -o /home/ploppz/work/rust/GFX/gfx/target/doc -L dependency=/home/ploppz/work/rust/GFX/gfx/target/debug/deps --extern winapi=/home/ploppz/work/rust/GFX/gfx/target/debug/deps/libwinapi-211def32813735d5.rlib` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: Could not compile `core-foundation-sys`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

As a side note, I wanted to view documentation across all gfx crates because I can't find any holistic documentation or up-to-date tutorials.

**Comment by msiglreith** [comment]
You probably need to exclude a few of the crates as  done for the [travis build](https://github.com/gfx-rs/gfx/blob/master/scripts/travis-script.sh#L10-L32).
Please keep in mind that `master` is quite unstable atm and you might want to stick to `v0.16` or `pre-ll` branch.

**Comment by Ploppz** [comment]
```
((HEAD detached at origin/v0.16)) $ cargo build                     
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching version `= 0.14.0` found for package `gfx_device_gl` (required by `gfx_app`)
location searched: file:///home/ploppz/work/rust/GFX/gfx/src/backend/gl
versions found: 0.14.2
consider running `cargo update` to update a path dependency's locked version
```

**Comment by Ploppz** [comment]
Yes thanks, `v0.16` worked fine.
