### ISSUE TITLE
vulkan: master branch 'quad' example crashes while resizing the window

### ISSUE THREAD

**Issue by ccll** [gfx-rs/gfx#1780]
Short info header:
'quad' example crashes with an error 'Unable to acquire a swapchain image: ErrorOutOfDateKhr' while resizing the window.

- GFX version: master branch - 48b3ef4
- OS: Ubuntu 17.10
- GPU: Intel(R) HD Graphics 530 (Skylake GT2)
- Backtrace:
```
AdapterInfo { name: "Intel(R) HD Graphics 530 (Skylake GT2)", vendor: 32902, device: 6418, software_rendering: false }
Surface format: Bgra8Srgb
Pipelines: [Ok(GraphicsPipeline(0x7f5a0132ae00))]
Memory types: [MemoryType { properties: DEVICE_LOCAL | COHERENT | CPU_VISIBLE | CPU_CACHED, heap_index: 0 }, MemoryType { properties: DEVICE_LOCAL | COHERENT | CPU_VISIBLE | CPU_CACHED, heap_index: 1 }]
thread 'main' panicked at 'Unable to acquire a swapchain image: ErrorOutOfDateKhr', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:799
  11: <gfx_backend_vulkan::window::Swapchain as gfx_hal::window::Swapchain<gfx_backend_vulkan::Backend>>::acquire_frame
             at /home/ccll/proj/gfx/src/backend/vulkan/src/window.rs:383
  12: quad::main
             at quad/main.rs:528
  13: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  14: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  15: main
  16: __libc_start_main
  17: _start
```

**Comment by kvark** [comment]
Thank you for submitting the issue!
We haven't got our hands on proper resizing in the examples yet.

**Comment by mpalomas** [comment]
Hi,

Same here on Windows 10 Pro, NVIDIA GTX 1050 drivers 391.35. I'm talking about the Vulkan renderer, it seems D3D12 handles resizing properly.

`    Finished dev [unoptimized + debuginfo] target(s) in 0.36 secs
     Running `C:\dev\rust\gfx\target\debug\quad.exe`
AdapterInfo { name: "GeForce GTX 1050", vendor: 4318, device: 7309, software_rendering: false }
Surface format: Bgra8Srgb
Memory types: [MemoryType { properties: (empty), heap_index: 1 }, MemoryType { properties: (empty), heap_index: 1 }, MemoryType { properties: (empty), heap_index: 1 }, MemoryType { properties: (empty), heap_index: 1 }, MemoryType { properties: (empty), heap_index: 1 }, MemoryType { properties: (empty), heap_index: 1 }, MemoryType { properties: (empty), heap_index: 1 }, MemoryType { properties: DEVICE_LOCAL, heap_index: 0 }, MemoryType { properties: DEVICE_LOCAL, heap_index: 0 }, MemoryType { properties: COHERENT | CPU_VISIBLE, heap_index: 1 }, MemoryType { properties: COHERENT | CPU_VISIBLE | CPU_CACHED, heap_index: 1 }]
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Success`,
 right: `ErrorOutOfDateKhr`', src\backend\vulkan\src\lib.rs:731:9
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:205
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:221
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:457
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:344
   7: gfx_backend_vulkan::{{impl}}::present<core::option::Option<mut gfx_backend_vulkan::window::Swapchain*>,[gfx_backend_vulkan::native::Semaphore; 0]*>
             at \<panic macros>:8
   8: gfx_hal::queue::CommandQueue<gfx_backend_vulkan::Backend, gfx_hal::queue::capability::Graphics>::present<gfx_backend_vulkan::Backend,gfx_hal::queue::capability::Graphics,core::option::Option<mut gfx_backend_vulkan::window::Swapchain*>,[gfx_backend_vulkan::native::Semaphore; 0]*>
             at C:\dev\rust\gfx\src\hal\src\queue\mod.rs:113
   9: gfx_hal::window::Swapchain::present<gfx_backend_vulkan::window::Swapchain,gfx_backend_vulkan::Backend,gfx_hal::queue::capability::Graphics,[gfx_backend_vulkan::native::Semaphore; 0]*>
             at C:\dev\rust\gfx\src\hal\src\window.rs:330
  10: quad::main
             at .\quad\main.rs:582

`

Your project sounds great, but it lacks documentation. Therefore we use code example to figure out, and having basic window resizing  would really help!

Thanks!

**Comment by JohnDoneth** [comment]
It should be possible to close this issue due to resizing support in #2052 being merged.
