### ISSUE TITLE
Metal backend panics on surface lost instead of returning an error

### ISSUE THREAD

**Issue by skylersaleh** [gfx-rs/gfx#2214]
It appears that the current metal backend doesn't handle the surface lost condition gracefully, as the metal backend seems to just panic when this condition occurs, instead of returning an error. Under Mac OS 10.13.4, surface lost is a pretty common situation as it occurs when a window is minimized or a the user switches to a different space.  

This causes any program that uses the metal backend and produces a window to crash when the window is minimized. This can be reproduced by running the Quad example on the metal backend and minimizing the window. 

The backtrace of this crash is shown below:
```
AdapterInfo { name: "Intel HD Graphics 5000", vendor: 0, device: 0, software_rendering: false }
Memory types: [MemoryType { properties: DEVICE_LOCAL, heap_index: 0 }, MemoryType { properties: COHERENT | CPU_VISIBLE, heap_index: 1 }, MemoryType { properties: DEVICE_LOCAL | CPU_VISIBLE, heap_index: 1 }, MemoryType { properties: DEVICE_LOCAL | CPU_VISIBLE | CPU_CACHED, heap_index: 1 }]
Surface format: Bgra8Srgb
Surface format: Bgra8Srgb
Surface format: Bgra8Srgb
Surface format: Bgra8Srgb
thread 'main' panicked at 'Surface lost?', libcore/option.rs:914:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore/result.rs:945:5
stack backtrace:
   0:        0x10443693f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h46a1c6e550992bcb
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:        0x104421f8d - std::sys_common::backtrace::print::h31e2c653a3f73623
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:        0x10443c721 - std::panicking::default_hook::{{closure}}::hbbf0c8c6327c5fdb
                               at libstd/panicking.rs:211
   3:        0x10443c41a - std::panicking::default_hook::h6e75a6a146dae005
                               at libstd/panicking.rs:227
   4:        0x10443cde1 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::h4d8827552603162e
                               at libstd/panicking.rs:463
   5:        0x10443c920 - std::panicking::try::do_call::hdc43d39d65cfc7d4
                               at libstd/panicking.rs:350
   6:        0x10443c8e2 - std::panicking::try::do_call::hdc43d39d65cfc7d4
                               at libstd/panicking.rs:328
   7:        0x1044680c5 - <&'a T as core::fmt::Display>::fmt::h6f282bb326e37d2b
                               at libcore/panicking.rs:71
   8:        0x103ef85f8 - <usize as core::iter::range::Step>::steps_between::hb19d2d018d6fcf25
                               at /private/tmp/rust-20180621-77208-nykn97/rustc-1.27.0-src/src/libcore/macros.rs:26
   9:        0x103ef422f - <u8 as core::iter::range::Step>::add_usize::h49c4968a387cf32d
                               at /private/tmp/rust-20180621-77208-nykn97/rustc-1.27.0-src/src/libcore/result.rs:782
  10:        0x103ecf5d3 - gfx_backend_metal::window::SurfaceInner::next_frame::{{closure}}::h3e637a4d5c400158
                               at /Users/skylersaleh/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/f095c19/src/backend/metal/src/window.rs:105
  11:        0x103c20f54 - core::ptr::drop_in_place::he40562b4b284d2db
                               at /private/tmp/rust-20180621-77208-nykn97/rustc-1.27.0-src/src/libcore/ptr.rs:59
  12:        0x103c57473 - hellogfx::main::h9f57eef8e838bb9d
                               at src/main.rs:541
  13:        0x103c35ff1 - std::rt::lang_start::{{closure}}::h4aa9b388b09b1806
                               at /private/tmp/rust-20180621-77208-nykn97/rustc-1.27.0-src/src/libstd/rt.rs:74
  14:        0x10443c847 - std::panicking::try::do_call::hdc43d39d65cfc7d4
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:310
  15:        0x104442dfe - panic_unwind::dwarf::eh::read_encoded_pointer::hbcb50d25193f07ab
                               at libpanic_unwind/lib.rs:105
  16:        0x10442f851 - std::sys_common::bytestring::debug_fmt_bytestring::ha68e8ce8308ca0c7
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:374
                               at libstd/rt.rs:58
  17:        0x103c35fd1 - std::rt::lang_start::h202231cef8d9fb0e
                               at /private/tmp/rust-20180621-77208-nykn97/rustc-1.27.0-src/src/libstd/rt.rs:74
  18:        0x103c59824 - hellogfx::swapchain_stuff::h074d499d25405239
thread panicked while panicking. aborting.

Command terminated
```

Short info header:
- GFX version: f095c19ad85c21c3bc287b483128a28bda3fb625
- OS: Mac OS X
- GPU: Intel HD 5000

**Comment by kvark** [comment]
Thanks for filing the issue @skylersaleh ! Our window system integration has been recently rewritten from scratch, is fairly hacky, and definitely missing proper surface lost handling.
