### ISSUE TITLE
Resizing window causing panic with vulkan backend in quad example

### ISSUE THREAD

**Issue by scott-wilson** [gfx-rs/gfx#2467]
Short info header:
- GFX version: Revision f288599e34e536ee406edd3cab81589ab29dc784
- OS: Kubuntu 18.04
- GPU: GeForce GTX 1050 Ti

I don't know if this is related to #1780, but when I do `cargo run --bin quad --features vulkan`, and resize the window constantly, I get the following errors/panic backtrace:

## Before panic

```
AdapterInfo { name: "GeForce GTX 1050 Ti", vendor: 4318, device: 7298, device_type: DiscreteGpu }
Memory types: [MemoryType { properties: (empty), heap_index: 1 }, MemoryType { properties: (empty), heap_index: 1 }, MemoryType { properties: (empty), heap_index: 1 }, MemoryType { properties: (empty), heap_index: 1 }, MemoryType { properties: (empty), heap_index: 1 }, MemoryType { properties: (empty), heap_index: 1 }, MemoryType { properties: (empty), heap_index: 1 }, MemoryType { properties: DEVICE_LOCAL, heap_index: 0 }, MemoryType { properties: DEVICE_LOCAL, heap_index: 0 }, MemoryType { properties: COHERENT | CPU_VISIBLE, heap_index: 1 }, MemoryType { properties: COHERENT | CPU_VISIBLE | CPU_CACHED, heap_index: 1 }]
formats: Some([Bgra8Unorm, Bgra8Srgb])
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 1024, height: 768 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
resized to LogicalSize { width: 1024.0, height: 768.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 1024, height: 768 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
resized to LogicalSize { width: 1021.0, height: 753.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 1021, height: 753 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
ERROR 2018-11-10T20:51:13Z: gfx_backend_vulkan: [DS] Object: 0x7f639c779000 | vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
resized to LogicalSize { width: 978.0, height: 577.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 978, height: 577 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
ERROR 2018-11-10T20:51:13Z: gfx_backend_vulkan: [DS] Object: 0x7f639c779000 | vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
resized to LogicalSize { width: 824.0, height: 289.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 824, height: 289 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
ERROR 2018-11-10T20:51:13Z: gfx_backend_vulkan: [DS] Object: 0x7f639c779000 | vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
resized to LogicalSize { width: 526.0, height: 207.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 526, height: 207 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
ERROR 2018-11-10T20:51:13Z: gfx_backend_vulkan: [DS] Object: 0x7f639c779000 | vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
resized to LogicalSize { width: 376.0, height: 405.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 376, height: 405 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [DS] Object: 0x7f639c779000 | vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
resized to LogicalSize { width: 604.0, height: 571.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 604, height: 571 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [DS] Object: 0x7f639c779000 | vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
resized to LogicalSize { width: 856.0, height: 507.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 856, height: 507 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [DS] Object: 0x7f639c779000 | vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
resized to LogicalSize { width: 886.0, height: 377.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 886, height: 377 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [DS] Object: 0x7f639c779000 | vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
resized to LogicalSize { width: 721.0, height: 418.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 721, height: 418 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [DS] Object: 0x7f639c779000 | vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
resized to LogicalSize { width: 763.0, height: 730.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 763, height: 730 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [DS] Object: 0x7f639c779000 | vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
resized to LogicalSize { width: 1037.0, height: 650.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 1037, height: 650 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [DS] Object: 0x7f639c779000 | vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
resized to LogicalSize { width: 997.0, height: 382.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 997, height: 382 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [DS] Object: 0x7f639c779000 | vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
resized to LogicalSize { width: 779.0, height: 424.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 779, height: 424 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [DS] Object: 0x7f639c779000 | vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
resized to LogicalSize { width: 727.0, height: 696.0 }
SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 727, height: 696 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [DS] Object: 0x7f639c779000 | vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
```

## Panic

```
thread 'main' panicked at 'internal error: entered unreachable code: Unexpected result - driver bug? Err(ErrorInitializationFailed)', src/backend/vulkan/src/device.rs:1709:18
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:346
   7: gfx_backend_vulkan::device::<impl gfx_hal::device::Device<gfx_backend_vulkan::Backend> for gfx_backend_vulkan::Device>::create_swapchain
             at src/backend/vulkan/src/device.rs:1709
   8: quad::main
             at examples/quad/main.rs:586
   9: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  10: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  12: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  13: std::rt::lang_start
             at libstd/rt.rs:74
  14: main
  15: __libc_start_main
  16: _start
```

## After panic

```
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f639e587908 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f639e587908 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f639e587208 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f639e587208 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f639e586b08 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f639e586b08 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f639e586408 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f639e586408 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f639e585d08 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f639e585d08 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f6398738508 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f6398738508 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f639e585608 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f639e585608 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f639e583308 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f639e583308 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f639e582c08 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f639e582c08 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f639e583a08 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f639e583a08 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f6398737008 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f6398737008 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f639e584108 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f639e584108 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f6398737708 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f6398737708 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f639e584808 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f639e584808 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f6398737e08 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f6398737e08 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7f639e584f08 | OBJ ERROR : For device 0x7f639c779000, CommandBuffer object 0x7f639e584f08 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0xe | OBJ ERROR : For device 0x7f639c779000, Semaphore object 0xe has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0xf | OBJ ERROR : For device 0x7f639c779000, Fence object 0xf has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0xb | OBJ ERROR : For device 0x7f639c779000, DeviceMemory object 0xb has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7 | OBJ ERROR : For device 0x7f639c779000, DeviceMemory object 0x7 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x9 | OBJ ERROR : For device 0x7f639c779000, DeviceMemory object 0x9 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x8 | OBJ ERROR : For device 0x7f639c779000, Buffer object 0x8 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x6 | OBJ ERROR : For device 0x7f639c779000, Buffer object 0x6 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0xa | OBJ ERROR : For device 0x7f639c779000, Image object 0xa has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7b | OBJ ERROR : For device 0x7f639c779000, ImageView object 0x7b has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7a | OBJ ERROR : For device 0x7f639c779000, ImageView object 0x7a has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0xc | OBJ ERROR : For device 0x7f639c779000, ImageView object 0xc has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x18 | OBJ ERROR : For device 0x7f639c779000, PipelineLayout object 0x18 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x13 | OBJ ERROR : For device 0x7f639c779000, RenderPass object 0x13 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x1b | OBJ ERROR : For device 0x7f639c779000, Pipeline object 0x1b has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x3 | OBJ ERROR : For device 0x7f639c779000, DescriptorSetLayout object 0x3 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0xd | OBJ ERROR : For device 0x7f639c779000, Sampler object 0xd has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x4 | OBJ ERROR : For device 0x7f639c779000, DescriptorPool object 0x4 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x5 | OBJ ERROR : For device 0x7f639c779000, DescriptorSet object 0x5 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7d | OBJ ERROR : For device 0x7f639c779000, Framebuffer object 0x7d has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x7c | OBJ ERROR : For device 0x7f639c779000, Framebuffer object 0x7c has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x2 | OBJ ERROR : For device 0x7f639c779000, CommandPool object 0x2 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x77 | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x77 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x70 | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x70 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x69 | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x69 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x62 | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x62 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x5b | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x5b has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x4d | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x4d has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x46 | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x46 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x3f | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x3f has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x1c | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x1c has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x23 | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x23 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x2a | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x2a has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x31 | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x31 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x38 | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x38 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x54 | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x54 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
ERROR 2018-11-10T20:51:14Z: gfx_backend_vulkan: [ObjectTracker] Object: 0x10 | OBJ ERROR : For device 0x7f639c779000, SwapchainKHR object 0x10 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
```

**Comment by bbrown683** [comment]
Can you see if it panics on my swapchain_cleanup branch referred to in #2464?

**Comment by scott-wilson** [comment]
Yup, no more panics with that branch.
