### ISSUE TITLE
Mystery crash on what should be a trivial change?

### ISSUE THREAD

**Issue by icefoxen** [gfx-rs/gfx#2572]
Short info header:
- GFX version: gfx-hal 0.1, gfx-backend-vulkan 0.1
- OS: Linux
- GPU: Intel HD 530

Built the `quad` example from git and it runs fine.  I made some minor changes to it: https://github.com/ggez/ggraphics/blob/cd4da7caeb58e5cf6dc5f2c05ff3996bc022bbfc/src/main.rs#L70-L117 which I don't THINK should have changed anything.  Now it panics on line 145, unwrapping `adapter.open_with::<_, hal::Graphics>(1, |family| surface.supports_queue_family(family))`

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InitializationFailed', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at libcore/result.rs:808
  10: ggraphics::main
             at src/main.rs:145
  11: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start
```

![image](https://user-images.githubusercontent.com/1335133/51211231-ebd82f80-18e2-11e9-8395-da1b267ad4d1.png)

**Comment by msiglreith** [comment]
Your instance is sad as it got dropped after creation [immediately](https://github.com/ggez/ggraphics/blob/cd4da7caeb58e5cf6dc5f2c05ff3996bc022bbfc/src/main.rs#L128-L134).
Look at this [catsample](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1865e4023e0ca662bdeb60c292825f67)
