### ISSUE TITLE
Vulkan on Windows, debug: Unable to load create_debug_utils_messenger_ext

### ISSUE THREAD

**Issue by nicbn** [gfx-rs/gfx#2621]
Short info header:
- GFX version: Latest git version
- OS: Windows 10
- GPU: AMD Radeon HD 7800 Series
Vulkan API version: 1.0.65

Running any of the examples on Windows with vulkan throws `Unable to load create_debug_utils_messenger_ext`.

Using --release won't trigger the error.

Stack trace from colour_uniform (Some path parts ommitted):
```
thread 'main' panicked at 'Unable to load create_debug_utils_messenger_ext', .cargo\registry\src\github.com\ash-0.27.1\src\vk.rs:46123:21
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at /rustc/src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys::windows::backtrace::set_frames
             at /rustc/src\libstd\sys\windows\backtrace\mod.rs:104
   3: std::sys_common::backtrace::print
             at /rustc/src\libstd\sys_common\backtrace.rs:60
   4: std::sys_common::backtrace::print
             at /rustc/src\libstd\sys_common\backtrace.rs:60
   5: std::panicking::default_hook
             at /rustc/src\libstd\panicking.rs:225
   6: std::panicking::rust_panic_with_hook
             at /rustc/src\libstd\panicking.rs:488
   7: std::panicking::begin_panic<str*>
             at /rustc/src\libstd\panicking.rs:422
   8: ash::vk::{{impl}}::load::create_debug_utils_messenger_ext
             at .cargo\registry\src\github.com-1ecc6299db9ec823\ash-0.27.1\src\vk.rs:46123
   9: ash::vk::ExtDebugUtilsFn::create_debug_utils_messenger_ext
             at .cargo\registry\src\github.com-1ecc6299db9ec823\ash-0.27.1\src\vk.rs:46235
  10: ash::extensions::ext::debug_utils::DebugUtils::create_debug_utils_messenger
             at .cargo\registry\src\github.com-1ecc6299db9ec823\ash-0.27.1\src\extensions\ext\debug_utils.rs:108
  11: gfx_backend_vulkan::Instance::create
             at gfx-master\src\backend\vulkan\src\lib.rs:361
  12: colour_uniform::create_backend
             at .\colour-uniform\main.rs:659
  13: colour_uniform::main
             at .\colour-uniform\main.rs:1671
  14: std::rt::lang_start::{{closure}}<()>
             at /rustc\src\libstd\rt.rs:74
  15: std::rt::lang_start_internal::{{closure}}
             at /rustc/src\libstd\rt.rs:59
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/src\libstd\rt.rs:59
  17: panic_unwind::__rust_maybe_catch_panic
             at /rustc/src\libpanic_unwind\lib.rs:102
  18: std::panicking::try
             at /rustc/src\libstd\panicking.rs:286
  19: std::panicking::try
             at /rustc/src\libstd\panicking.rs:286
  20: std::panicking::try
             at /rustc/src\libstd\panicking.rs:286
  21: std::rt::lang_start<()>
             at /rustc/src\libstd\rt.rs:74
  22: main
  23: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  24: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  25: BaseThreadInitThunk
  26: RtlUserThreadStart
error: process didn't exit successfully: `gfx-master\target\debug\colour-uniform.exe` (exit code: 3221225501)
Illegal instruction
```

**Comment by kvark** [comment]
cc @bzm3r of #2373
somehow, I fail to look "VK_EXT_debug_utils" up at https://vulkan.gpuinfo.org/listextensions.php

**Comment by bzm3r** [comment]
@kvark 

https://vulkan.lunarg.com/doc/view/1.1.82.1/windows/layer_configuration.html (ctrl+ f for "VK_EXT_debug_utils"

https://www.lunarg.com/new-tutorial-for-vulkan-debug-utilities-extension/

Does the LunarG Vulkan SDK need to be installed specifically?

**Comment by nicbn** [comment]
I did not have LunarG SDK installed however the problem wasn't solved by installing it.
I installed it at `C:\dev\VulkanSDK\1.1.97.0` and set `VULKAN_SDK` and `VK_SDK_PATH` to that. I also added `%VULKAN_SDK%\bin` to `Path`.
Is there anything I'm missing?

**Comment by kvark** [comment]
I was looking at the device extension list, while this is an instance extension. Apparently, it's not supported on some platforms, like GeForce gtx 750 and Radeon R2... we need to make our run-time aware of this and ignore the calls.

**Comment by bzm3r** [comment]
@kvark also, maybe fallback to the old debug_report?

**Comment by kvark** [comment]
Only if it covers all the platforms where the current ext isn't available.

**Comment by kvark** [comment]
@bzm3r this just hit me as well. Would you have time to work on it?

**Comment by bzm3r** [comment]
hi all -- sorry i still haven't had a chance to address this (quite busy atm!); i promise to keep it on my radar

**Comment by Gordon-F** [comment]
Same issue on Android ?

```bash
05-19 15:32:58.656 18274 18296 D RustAndroidGlueStdouterr: Creating application thread
05-19 15:32:58.761 18274 18297 D RustAndroidGlueStdouterr: thread 'main' panicked at 'Unable to load create_debug_utils_messenger_ext', /Users/indish/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.29.0/src/vk.rs:53262:21
05-19 15:32:58.766 18274 18297 D RustAndroidGlueStdouterr: stack backtrace:
05-19 15:32:58.767 18274 18297 D RustAndroidGlueStdouterr:    0: <unknown>
05-19 15:32:58.767 18274 18297 D RustAndroidGlueStdouterr:    1: <unknown>
05-19 15:32:58.768 18274 18297 D RustAndroidGlueStdouterr:    2: <unknown>
05-19 15:32:58.768 18274 18297 D RustAndroidGlueStdouterr:    3: <unknown>
05-19 15:32:58.769 18274 18297 D RustAndroidGlueStdouterr:    4: std::panicking::rust_panic_with_hook
05-19 15:32:58.769 18274 18297 D RustAndroidGlueStdouterr:    5: std::panicking::begin_panic
05-19 15:32:58.769 18274 18297 D RustAndroidGlueStdouterr:    6: ash::vk::ExtDebugUtilsFn::load::create_debug_utils_messenger_ext
05-19 15:32:58.770 18274 18297 D RustAndroidGlueStdouterr:    7: ash::vk::ExtDebugUtilsFn::create_debug_utils_messenger_ext
05-19 15:32:58.770 18274 18297 D RustAndroidGlueStdouterr:    8: ash::extensions::ext::debug_utils::DebugUtils::create_debug_utils_messenger
05-19 15:32:58.770 18274 18297 D RustAndroidGlueStdouterr:    9: gfx_backend_vulkan::Instance::create
05-19 15:32:58.770 18274 18297 D RustAndroidGlueStdouterr:   10: game_lib::main_rs
05-19 15:32:58.771 18274 18297 D RustAndroidGlueStdouterr:   11: <unknown>
05-19 15:32:58.771 18274 18297 D RustAndroidGlueStdouterr:   12: <unknown>
05-19 15:32:58.772 18274 18297 D RustAndroidGlueStdouterr:   13: <unknown>
05-19 15:32:58.772 18274 18297 D RustAndroidGlueStdouterr:   14: __rust_maybe_catch_panic
05-19 15:32:58.772 18274 18297 D RustAndroidGlueStdouterr:   15: std::rt::lang_start_internal
05-19 15:32:58.772 18274 18297 D RustAndroidGlueStdouterr:   16: <unknown>
05-19 15:32:58.772 18274 18297 D RustAndroidGlueStdouterr:   17: main
05-19 15:32:58.773 18274 18297 D RustAndroidGlueStdouterr:   18: <unknown>
05-19 15:32:58.773 18274 18297 D RustAndroidGlueStdouterr:   19: <unknown>
05-19 15:32:58.773 18274 18297 D RustAndroidGlueStdouterr:   20: <unknown>
05-19 15:32:58.773 18274 18297 D RustAndroidGlueStdouterr:   21: <unknown>
```

**Comment by bzm3r** [comment]
@kvark Do you still have access to the Windows machine which was causing issues with DebugUtils in the past? I am wondering if you are still able to reproduce the issue on it, after making sure that you've installed the newest Vulkan SDK?

**Comment by kvark** [comment]
I can run wgpu-rs on all of my machines now, so this must be fixed :)
