### ISSUE TITLE
Possible to run compute on arm / OpenGL ES 3.1?

### ISSUE THREAD

**Issue by MarkSwanson** [gfx-rs/gfx#3085]
Short info header:
- GFX version:
Nov 9, 2019 git master.
- OS:
raspbian / Linux 4.19.75-v7l+  (Raspberry Pi 4b armv7)
- GPU:
Broadcom VideoCore VI / Mesa 

$ <everything compiles/builds fine>
$ cargo run --bin compute --features gl 1 2 3 4
You need to enable one of the next-gen API feature (vulkan, dx12, metal) to run this example.

I'm curious if supporting this would be on the roadmap?
I'm just interested in playing with compute. I'm sure I have other options - like using the FFI wrappers around libgles2-mesa. I'm just looking for a good way to take advantage of the GPU. I'd like to run some high frame rate algorithms on the camera images.

Thanks!

**Comment by kvark** [comment]
The `compute` example just doesn't have GL support. It needs to be added, and from what I see - OpenGL ES 3.1 on ARM should have compute shaders. Want to try adding GL support to the example and test it?

**Comment by MarkSwanson** [comment]
Ok, I created a fork to play with this: git@github.com:MarkSwanson/gfx.git
(it's GL-specific, I just realized I now have a headless issue)

I get 'CompilationFailed' here:
let shader = match self.create_shader_module_from_source(&glsl, stage).unwrap()

...
16: gfx_backend_gl::device::Device::compile_shader
             at src/backend/gl/src/device.rs:396
  17: <gfx_backend_gl::device::Device as gfx_hal::device::Device<gfx_backend_gl::Backend>>::create_compute_pipeline
             at src/backend/gl/src/device.rs:917
  18: compute::main
             at examples/compute/main.rs:115

I'm interested in doing the work to finish this, but I need some help/guidance on how to get past the 'CompilationFailed' problem.

Thanks!

**Comment by MarkSwanson** [comment]
Just a fyi - the above 'CompilationFailed' error was on an Ubuntu 18.04.3 system with the nvidia 435.21 driver.

I just compiled/ran this on a amdgpu system (Ubuntu 18.04.3, amdgpu-pro-19.30-934563 driver) and saw the same 'CompilationFailed' error with a bit more debug/error output:
(just it case it's helpful)

[2019-11-11T05:31:28Z ERROR winit::platform_impl::platform] X11 error: XError {
    description: "BadValue (integer parameter out of range for operation)",
    error_code: 2,
    request_code: 53,
    minor_code: 0,
}
[2019-11-11T05:31:28Z ERROR winit::platform_impl::platform] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 154,
    minor_code: 3,
}
[2019-11-11T05:31:28Z ERROR winit::platform_impl::platform] X11 error: XError {
    description: "BadDrawable (invalid Pixmap or Window parameter)",
    error_code: 9,
    request_code: 154,
    minor_code: 12,
}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationFailed("")', src/libcore/result.rs:1165:5

**Comment by kvark** [comment]
The output you posted has nothing to do with the compilation error, for the most part. It means the window-system integration is broken for some reason. Happened to me on Vulkan if the system isn't configured, but I don't know why you'd get it on OpenGL.

**Comment by MarkSwanson** [comment]
Looked at this again.
The 'out of range' error was because I was specifying a Glutin headless 0x0 PhysicalSize. Setting that to 1280.0, 720.0 fixed that BadValue/BadDrawable, but didn't help get compute working.

It's strange that vulkan will work on the AMD box (amd pro drivers with rx580), but gl will not.
So still same error on Raspbery Pi 4, and AMD64 with RX580.
The AMD quad gl demo works fine too, just not gl compute.

**Comment by kvark** [comment]
@MarkSwanson strange indeed, but also - there shouldn't be much work needed to get it work, since it works on other platforms. Can you make an `apitrace` capture?
