### ISSUE TITLE
'Unexpected wait status 0xFFFFFFFF' in gfx-backend-dx12 when device is dropped with SDL2

### ISSUE THREAD

**Issue by parasyte** [gfx-rs/gfx#3088]
Short info header:
- GFX version: `wgpu = "0.4.0", wgpu-native = "0.4.0", gfx-backend-dx12 = "0.4.1"`
- OS: `Windows 10, Version: 1903, OS Build: 18362.418`
- GPU: `Intel HD Graphics P4000`

```
[2019-11-11T00:04:31Z INFO  wgpu_native::instance] Adapter Dx12 AdapterInfo { name: "Microsoft Basic Render Driver", vendor: 5140, device: 140, device_type: VirtualGpu }
```

This panic only occurs in debug builds, only semi-frequently, and only upon closing the SDL2 window. An example that can reproduce the panic is [here](https://github.com/parasyte/pixels/blob/d4e4fc4332488b7f307d3a27d25cea600b2a56fe/examples/minimal-sdl2/main.rs). Build instructions are in [the README](https://github.com/parasyte/pixels/tree/d4e4fc4332488b7f307d3a27d25cea600b2a56fe/examples/minimal-sdl2).

<details><summary>thread 'main' panicked at 'Unexpected wait status 0xFFFFFFFF'</summary>

```
thread 'main' panicked at 'Unexpected wait status 0xFFFFFFFF', C:\Users\jay\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.4.1\src\device.rs:3233:18
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.34\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:200
   4: std::panicking::default_hook
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:214
   5: std::panicking::rust_panic_with_hook
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:477
   6: std::panicking::continue_panic_fmt
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:384
   7: std::panicking::begin_panic_fmt
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:339
   8: gfx_backend_dx12::device::{{impl}}::wait_for_fences<core::iter::adapters::Map<core::slice::Iter<wgpu_native::device::ActiveSubmission<gfx_backend_dx12::Backend>>, closure-0>>
             at <::std::macros::panic macros>:8
   9: wgpu_native::device::PendingResources<gfx_backend_dx12::Backend>::cleanup<gfx_backend_dx12::Backend>
             at C:\Users\jay\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-native-0.4.0\src\device.rs:216
  10: wgpu_native::device::Device<gfx_backend_dx12::Backend>::maintain<gfx_backend_dx12::Backend>
             at C:\Users\jay\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-native-0.4.0\src\device.rs:587
  11: wgpu_native::device::device_poll<gfx_backend_dx12::Backend>
             at C:\Users\jay\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-native-0.4.0\src\device.rs:2133
  12: wgpu_native::device::wgpu_device_poll
             at C:\Users\jay\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-native-0.4.0\src\device.rs:2141
  13: wgpu::{{impl}}::drop
             at C:\Users\jay\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.4.0\src\lib.rs:841
  14: core::ptr::real_drop_in_place<wgpu::Device>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libcore\ptr\mod.rs:175
  15: core::ptr::real_drop_in_place<alloc::rc::RcBox<wgpu::Device>>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libcore\ptr\mod.rs:175
  16: core::ptr::drop_in_place
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libcore\ptr\mod.rs:165
  17: alloc::rc::{{impl}}::drop<wgpu::Device>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\liballoc\rc.rs:922
  18: core::ptr::real_drop_in_place<alloc::rc::Rc<wgpu::Device>>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libcore\ptr\mod.rs:175
  19: core::ptr::real_drop_in_place<pixels::renderers::Renderer>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libcore\ptr\mod.rs:175
  20: core::ptr::real_drop_in_place<alloc::boxed::Box<RenderPass>>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libcore\ptr\mod.rs:175
  21: core::ptr::real_drop_in_place<slice<alloc::boxed::Box<RenderPass>>>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libcore\ptr\mod.rs:175
  22: core::ptr::drop_in_place
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libcore\ptr\mod.rs:165
  23: alloc::vec::{{impl}}::drop<alloc::boxed::Box<RenderPass>>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\liballoc\vec.rs:2232
  24: core::ptr::real_drop_in_place<alloc::vec::Vec<alloc::boxed::Box<RenderPass>>>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libcore\ptr\mod.rs:175
  25: core::ptr::real_drop_in_place<pixels::Pixels>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libcore\ptr\mod.rs:175
  26: minimal_sdl2::main
             at .\examples\minimal-sdl2\main.rs:72
  27: std::rt::lang_start::{{closure}}<core::result::Result<(), alloc::string::String>>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\rt.rs:64
  28: std::rt::lang_start_internal::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\rt.rs:49
  29: std::panicking::try::do_call<closure-0,i32>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:296
  30: panic_unwind::__rust_maybe_catch_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libpanic_unwind\lib.rs:80
  31: std::panicking::try
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:275
  32: std::panic::catch_unwind
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panic.rs:394
  33: std::rt::lang_start_internal
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\rt.rs:48
  34: std::rt::lang_start<core::result::Result<(), alloc::string::String>>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\rt.rs:64
  35: main
  36: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  37: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  38: BaseThreadInitThunk
  39: RtlUserThreadStart
```
</details>

**Comment by kvark** [comment]
It's not clear if the bug is in wgpu or here, but this place is good to kick off that investigation - we can move the issue later.
