### ISSUE TITLE
Cargo fmt failure

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3483]
Looks to be happening in the GL backend specifically
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/tools/rustfmt/src/lists.rs:678:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/tools/rustfmt/src/lists.rs:678:54
```

**Comment by kvark** [comment]
Filed upstream - https://github.com/rust-lang/rustfmt/issues/4552
