### ISSUE TITLE
Unable to run QUAD example

### ISSUE THREAD

**Issue by Lowentwickler** [gfx-rs/gfx#3509]
Short info header:
- GFX version: `master branch`
- OS: Mac, 20.1.0 Darwin Kernel Version, x86_64
- GPU: Intel(R) Iris(TM) Plus Graphics

```
RUST_BACKTRACE=1 cargo run --bin quad --features metal 
   Compiling hal-examples v0.1.0 (/Users/elias/Projects/gfx/examples)
    Finished dev [unoptimized + debuginfo] target(s) in 6.43s
     Running `/Users/elias/Projects/gfx/target/debug/quad`
AdapterInfo { name: "Intel(R) Iris(TM) Plus Graphics", vendor: 0, device: 0, device_type: IntegratedGpu }
Memory types: [MemoryType { properties: DEVICE_LOCAL, heap_index: 0 }, MemoryType { properties: CPU_VISIBLE | COHERENT, heap_index: 1 }, MemoryType { properties: DEVICE_LOCAL | CPU_VISIBLE, heap_index: 1 }, MemoryType { properties: DEVICE_LOCAL | CPU_VISIBLE | CPU_CACHED, heap_index: 1 }]
formats: Some([Bgra8Unorm, Bgra8Srgb, Rgba16Sfloat])
SwapchainConfig { present_mode: FIFO, composite_alpha_mode: OPAQUE, format: Bgra8Srgb, extent: Extent2D { width: 1024, height: 768 }, image_count: 3, image_layers: 1, image_usage: COLOR_ATTACHMENT }
thread 'main' panicked at 'assertion failed: self.state.render_pso_is_compatible', src/backend/metal/src/command.rs:4431:9
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/elias/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:497
   1: <gfx_backend_metal::command::CommandBuffer as gfx_hal::command::CommandBuffer<gfx_backend_metal::Backend>>::draw
             at /Users/elias/Projects/gfx/src/backend/metal/src/command.rs:4431
   2: quad::Renderer<B>::render
             at ./quad/main.rs:852
   3: quad::main
             at ./quad/main.rs:136
   4: core::ops::function::FnOnce::call_once
             at /Users/elias/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
DROPPED!
```

**Comment by kvark** [comment]
Oh wow, that's a pretty harsh failure, considering that `wgpu` runs fine.
I'll fix this ASAP.

**Comment by Lowentwickler** [comment]
Yes, wgpu works fine for me. I was surprised as well
