### ISSUE TITLE
Using gl_DepthRange in a fragment shader errors while creating a core batch

### ISSUE THREAD

**Issue by chwevans** [gfx-rs/gfx#840]
Using gl_DepthRange to set gl_FragDepth in a fragment shader causes building of the core to fail with the error: Parameters(MissingUniform("gl_DepthRange.near"))

**Comment by chwevans** [comment]
Example fragment shader code taken from the arcsynthesis tutorials:

```
vec4 clipPos = cameraToClipMatrix * vec4(cameraPos, 1.0);
float ndcDepth = clipPos.z / clipPos.w;
gl_FragDepth = ((gl_DepthRange.diff * ndcDepth) +
    gl_DepthRange.near + gl_DepthRange.far) / 2.0;
```

**Comment by kvark** [comment]
Thanks for the report! GL backend prints out everything it finds in a shader (e.g. [here](https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/shade.rs#L217)). Perhaps you could enable logging and check what it found?

**Comment by chwevans** [comment]
I enabled debug logging and didn't get anything more useful out of it. The code triggering it in question is
```
let (t_vs, t_fs, terrain_mesh) = terrain::core(128);
let source = factory.link_program_source(t_vs, t_fs).expect("Failed to link terrain source");
let terrain_core = gfx::batch::Core::new(factory.create_mesh(&terrain_mesh[..]), source).expect("Failed to create core: terrain");
```
The third line is what trips the error. Logging with debug enabled:
```
thread '<main>' panicked at 'Failed to create core: terrain: Parameters(MissingUniform("gl_DepthRange.near"))', src/libcore/result.rs:755
DEBUG:cargo: handle_error; err=CliError { error: Human(Process didn't exit successfully: `target/debug/simple_client` (exit code: 101)), unknown: false, exit_code: 101 }
Process didn't exit successfully: `target/debug/simple_client` (exit code: 101)
```

**Comment by kvark** [comment]
I don't think you got the logging correctly. Last time I checked, your app needs to call `env_logger::init().unwrap()` at start, and then you'd need to start with `RUST_LOG=debug <app>`.

This way you should see many info messages by the GL shader loading and reflection that our backend spews out.

**Comment by chwevans** [comment]
Ah, I was missing the ```env_logger::init().unwrap()```, had the environment variable.

```
INFO:gfx_device_gl: Vendor: "Intel Inc."
INFO:gfx_device_gl: Renderer: "Intel HD Graphics 5000 OpenGL Engine"
INFO:gfx_device_gl: Version: 4.1, INTEL-10.8.77
INFO:gfx_device_gl: Shading Language: 4.10
DEBUG:gfx_device_gl: Loaded Extensions:
DEBUG:gfx_device_gl: - GL_ARB_vertex_attrib_64bit
DEBUG:gfx_device_gl: - GL_ARB_explicit_attrib_location
DEBUG:gfx_device_gl: - GL_ARB_sampler_objects
DEBUG:gfx_device_gl: - GL_ARB_separate_shader_objects
DEBUG:gfx_device_gl: - GL_EXT_texture_compression_s3tc
DEBUG:gfx_device_gl: - GL_ARB_occlusion_query2
DEBUG:gfx_device_gl: - GL_ARB_ES2_compatibility
DEBUG:gfx_device_gl: - GL_ARB_gpu_shader5
DEBUG:gfx_device_gl: - GL_ARB_shading_language_include
DEBUG:gfx_device_gl: - GL_ARB_internalformat_query
DEBUG:gfx_device_gl: - GL_ARB_shader_bit_encoding
DEBUG:gfx_device_gl: - GL_EXT_debug_marker
DEBUG:gfx_device_gl: - GL_ARB_viewport_array
DEBUG:gfx_device_gl: - GL_ARB_texture_storage
DEBUG:gfx_device_gl: - GL_ARB_texture_buffer_object_rgb32
DEBUG:gfx_device_gl: - GL_APPLE_object_purgeable
DEBUG:gfx_device_gl: - GL_EXT_debug_label
DEBUG:gfx_device_gl: - GL_ARB_texture_cube_map_array
DEBUG:gfx_device_gl: - GL_ARB_texture_query_lod
DEBUG:gfx_device_gl: - GL_ARB_blend_func_extended
DEBUG:gfx_device_gl: - GL_ARB_vertex_type_2_10_10_10_rev
DEBUG:gfx_device_gl: - GL_NV_texture_barrier
DEBUG:gfx_device_gl: - GL_ARB_draw_indirect
DEBUG:gfx_device_gl: - GL_APPLE_texture_range
DEBUG:gfx_device_gl: - GL_APPLE_client_storage
DEBUG:gfx_device_gl: - GL_EXT_texture_sRGB_decode
DEBUG:gfx_device_gl: - GL_ARB_draw_buffers_blend
DEBUG:gfx_device_gl: - GL_ARB_texture_rgb10_a2ui
DEBUG:gfx_device_gl: - GL_APPLE_rgb_422
DEBUG:gfx_device_gl: - GL_ARB_texture_swizzle
DEBUG:gfx_device_gl: - GL_APPLE_container_object_shareable
DEBUG:gfx_device_gl: - GL_ARB_transform_feedback3
DEBUG:gfx_device_gl: - GL_EXT_framebuffer_multisample_blit_scaled
DEBUG:gfx_device_gl: - GL_ARB_tessellation_shader
DEBUG:gfx_device_gl: - GL_APPLE_row_bytes
DEBUG:gfx_device_gl: - GL_ARB_transform_feedback2
DEBUG:gfx_device_gl: - GL_APPLE_flush_render
DEBUG:gfx_device_gl: - GL_ARB_instanced_arrays
DEBUG:gfx_device_gl: - GL_ARB_timer_query
DEBUG:gfx_device_gl: - GL_ATI_texture_mirror_once
DEBUG:gfx_device_gl: - GL_ARB_gpu_shader_fp64
DEBUG:gfx_device_gl: - GL_ARB_texture_gather
DEBUG:gfx_device_gl: - GL_ARB_shader_subroutine
DEBUG:gfx_device_gl: - GL_EXT_texture_filter_anisotropic
DEBUG:gfx_device_gl: - GL_ARB_sample_shading
INFO:gfx_device_gl::factory: 	Created array buffer 1
INFO:gfx_device_gl::factory: 	Created frame buffer 1
INFO:gfx_device_gl::factory: 	Created frame buffer 2
INFO:gfx_device_gl::factory: 	Created buffer 1
INFO:gfx_device_gl::shade: 	Compiled shader 1
INFO:gfx_device_gl::shade: 	Compiled shader 2
INFO:gfx_device_gl::shade: 	Linked program 3
INFO:gfx_device_gl::shade: 		Uniform[0] = "u_RatioPosition"	F32	Vector(3)
INFO:gfx_device_gl::shade: 		Uniform[-1] = "gl_DepthRange.near"	F32	Single
INFO:gfx_device_gl::shade: 		Uniform[-1] = "gl_DepthRange.far"	F32	Single
INFO:gfx_device_gl::shade: 		Uniform[-1] = "gl_DepthRange.diff"	F32	Single
INFO:gfx_device_gl::shade: 		Uniform[1] = "u_RelativeDirection"	F32	Matrix(ColumnMajor, 4, 4)
INFO:gfx_device_gl::shade: 		Sampler[5] = "t_Color"	F32	Sampler2D(NoArray, NoShadow, NoMultiSample, NoRect)
INFO:gfx_device_gl::shade: 		Uniform[6] = "u_Projection"	F32	Matrix(ColumnMajor, 4, 4)
INFO:gfx_device_gl::shade: 		Attrib[0] = "a_Pos"	F32	Vector(2)
thread '<main>' panicked at 'Failed to create core: terrain: Parameters(MissingUniform("gl_DepthRange.near"))', src/libcore/result.rs:755
```

**Comment by kvark** [comment]
I guess we just need to check for `gl_` prefix and ignore these (why aren't we already?)

**Comment by chwevans** [comment]
Odd because using gl_FragDepth alone does not trigger this, although it is not a struct like gl_DepthRange is.
