### ISSUE TITLE
Panic when creating window: Err value DescriptorInit(PixelExport(255, None))

### ISSUE THREAD

**Issue by daboross** [gfx-rs/gfx#977]
This is an error that I've found when updating piston from an earlier version (0.19) to 0.22. This worked successfully on gfx v0.10.2, and errors on v0.11.0:

```
$ RUST_BACKTRACE=1 cargo run
     Running `target/debug/bw-adventures`
Successfully created first window
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: DescriptorInit(PixelExport(255, None))', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x55c0a0dfffd0 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x55c0a0e028bb - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x55c0a0e02528 - panicking::default_handler::h18faf4fbd296d909lSz
   4:     0x55c0a0df682c - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   5:     0x55c0a0df6cb8 - sys_common::unwind::begin_unwind_fmt::h8b491a76ae84af35m0t
   6:     0x55c0a0dff441 - rust_begin_unwind
   7:     0x55c0a0e31d3f - panicking::panic_fmt::h98b8cbb286f5298alcM
   8:     0x55c0a0ac09b4 - result::unwrap_failed::h6985425857571444624
                        at ../src/libcore/macros.rs:29
   9:     0x55c0a0ac0739 - result::Result<T, E>::unwrap::h17750157649990784447
                        at ../src/libcore/result.rs:687
  10:     0x55c0a0ac05c6 - gfx_graphics::back_end::Gfx2d<R>::new::_$u7b$$u7b$closure$u7d$$u7d$::closure.25451
                        at /home/daboross/.cargo/registry/src/github.com-88ac128001ac3a9a/piston2d-gfx_graphics-0.28.0/src/back_end.rs:215
  11:     0x55c0a0ac10b7 - back_end::PsoStencil<T>::new::h12884116355933234546
                        at /home/daboross/.cargo/registry/src/github.com-88ac128001ac3a9a/piston2d-gfx_graphics-0.28.0/src/back_end.rs:123
  12:     0x55c0a0aaf67f - back_end::Gfx2d<R>::new::h656842580009299534
                        at /home/daboross/.cargo/registry/src/github.com-88ac128001ac3a9a/piston2d-gfx_graphics-0.28.0/src/back_end.rs:230
  13:     0x55c0a0a974cf - PistonWindow<W>::new::h7085292114642368369
                        at /home/daboross/.cargo/registry/src/github.com-88ac128001ac3a9a/piston_window-0.47.0/src/lib.rs:191
  14:     0x55c0a0a93ab2 - run::h4275c3a05e788418njd
                        at src/rust/lib.rs:45
  15:     0x55c0a0a93788 - main::hbb8d27b139002075faa
                        at src/bin/bw-adventures.rs:4
  16:     0x55c0a0e02184 - sys_common::unwind::try::try_fn::h14622312129452522850
  17:     0x55c0a0dff3cb - __rust_try
  18:     0x55c0a0e01c1b - rt::lang_start::h0ba42f7a8c46a626rKz
  19:     0x55c0a0a937c9 - main
  20:     0x7f994390661f - __libc_start_main
  21:     0x55c0a0a93678 - _start
  22:                0x0 - <unknown>
Process didn't exit successfully: `target/debug/bw-adventures` (exit code: 101)
```

Here's the code which is triggering this:
```
let opengl_version = opengl_graphics::OpenGL::V3_0;

let mut window = {
    let settings = WindowSettings::new("b-w-adventures", [640u32, 480u32])
                        .exit_on_esc(false)
                        .opengl(opengl_version);

    let samples = settings.get_samples();

    let window = settings.build().unwrap();

    println!("Successfully created first window");

    PistonWindow::new(opengl_version, samples, window)
    // window
};
```

I haven't ever used glx directly, but only through piston_window. I hope the code example here is sufficient, I believe this error is due to glx and not a piston error. This occurs on the latest versions of piston, piston_window, gfx, etc. Cargo.lock: http://sprunge.us/ggUV. Occurs using both sdl2 and glutin.

I'm on Gentoo linux, info:
```
$ uname -a
Linux gentux 4.4.6-gentoo #3 SMP Mon May 16 23:41:48 PDT 2016 x86_64 Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz GenuineIntel GNU/Linux
$ lspci -k
...
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
	Subsystem: Dell 2nd Generation Core Processor Family Integrated Graphics Controller
	Kernel driver in use: i915
...
```

glxinfo: http://sprunge.us/BjaU

If this is not the correct place to report this, my apologies - I will just close this and open an issue in the correct location.

**Comment by kvark** [comment]
Thank you for the report, @daboross !
cc @csherratt

**Comment by daboross** [comment]
I should note one other thing: This system is a nvidia optimus system, just meaning it has two graphics cards. The error occurs both when using the intel card (info in original post), and when using the nvidia card via bumblebee (`01:00.0 VGA compatible controller: NVIDIA Corporation GF106M [GeForce GT 555M] (rev a1)`).

I would not think that optimus causes the error, as the intel card is run just as if it was the only graphics card, but it might be useful to know that it also happens when using nvidia card/drivers, not only on the intel card/drivers.

**Comment by Bastacyclop** [comment]
I have the same problem when I specify `OpenGL::V2_1` but not with `OpenGL::V3_2`.

**Comment by kvark** [comment]
It looks like we are not handling `ARB_program_interface_query` properly with GLSL-1.20 shaders.

**Comment by kvark** [comment]
One way to fix it is to properly handle `gl_FragData` and `gl_FragColor` in the new ARB queries. However, I don't think we want this.We don't want to support multiple render targets on GL pre-3.2 anyway, so the new queries don't help much there. Instead, there is a simpler way to fix this.

Check out the way we trigger the new query:
```rust
    // check to see if this will work
    if !gl.GetProgramInterfaceiv.is_loaded() {
        return None;
    }
```
And instead, we should be doing it via `caps`, like here:
```rust
    let num = if caps.constant_buffer_supported {
        get_program_iv(gl, prog, gl::ACTIVE_UNIFORM_BLOCKS)
    } else {
        0
    };
```
Where the new capability may require GL 3.2:
```rust
program_interface_supported: info.is_version_supported(3, 2),
```
The downside is - lack of support for multiple targets on GL-3.1 (and GLSL-140 correspondingly).
